version: "3"
services:
  db:
    image: postgres:14.4
    container_name: mapreduce-example-postgres-db
    restart: always
    ports:
      - "5432:5432"
    networks:
      - application
    environment:
      POSTGRES_DB: mapreduce-example-db
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  activemq:
    image: rmohr/activemq:5.15.9
    container_name: mapreduce-example-activemq
    restart: always
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - application

networks:
  application:
    driver: bridge
